# ===============================
# DATABASE (Render ENV variables)
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# IMPORTANT: Let Hibernate auto-detect dialect
spring.jpa.database-platform=

# ===============================
# SERVER
# ===============================
server.port=${PORT:8080}
